import * as vscode from 'vscode';

export default function generateStatsCommand(context: vscode.ExtensionContext) {
    return vscode.commands.registerCommand('typingspeedometer.showDetailedStats', async () => {
        // Get current session stats
        const sessionKeystrokes = context.globalState.get<number>('typingspeedometer.sessionKeystrokes', 0);
        const sessionCorrections = context.globalState.get<number>('typingspeedometer.sessionCorrections', 0);
        const sessionStartTime = new Date(context.globalState.get<Date>('typingspeedometer.sessionStartTime', new Date()));
        const currentTime = new Date();
        
        // Calculate current session metrics
        const sessionDuration = currentTime.getTime() - sessionStartTime.getTime();
        const sessionMinutes = sessionDuration / (1000 * 60);
        const sessionKPS = sessionDuration > 0 ? (sessionKeystrokes / sessionDuration) * 1000 : 0;
        const sessionWPM = sessionDuration > 0 ? (sessionKeystrokes / 5 / sessionDuration) * 60000 : 0;
        const sessionAccuracy = sessionKeystrokes > 0 ? ((sessionKeystrokes - sessionCorrections) / sessionKeystrokes) * 100 : 100;

        // Get high scores
        const highScoreKPS = context.globalState.get<number>('typingspeedometer.highScoreKPS', 0);
        const highScoreWPM = context.globalState.get<number>('typingspeedometer.highScoreWPM', 0);
        const highScoreAccuracy = context.globalState.get<number>('typingspeedometer.highScoreAccuracy', 0);

        const statsContent = `# 📊 Typing Speedometer - Detailed Statistics

## 📈 Current Session
- **Duration**: ${sessionMinutes.toFixed(1)} minutes
- **Keystrokes**: ${sessionKeystrokes}
- **Corrections**: ${sessionCorrections}
- **Speed**: ${sessionWPM.toFixed(1)} WPM (${sessionKPS.toFixed(1)} KPS)
- **Accuracy**: ${sessionAccuracy.toFixed(1)}%

## 🏆 Personal Records
- **Best Speed**: ${highScoreWPM.toFixed(1)} WPM (${highScoreKPS.toFixed(1)} KPS)
- **Best Accuracy**: ${highScoreAccuracy.toFixed(1)}%

## 📝 Tips for Improvement
- **Speed**: Practice touch typing and maintain consistent rhythm
- **Accuracy**: Focus on precision over speed - accuracy builds muscle memory
- **Sessions**: Take breaks every 30 minutes to maintain peak performance

---
*Generated by Typing Speedometer Extension*
*Export Date: ${new Date().toLocaleString()}*
`;

        try {
            const document = await vscode.workspace.openTextDocument({
                content: statsContent,
                language: 'markdown'
            });
            await vscode.window.showTextDocument(document);
        } catch (error) {
            vscode.window.showErrorMessage('Failed to display detailed statistics');
        }
    });
}